# Generated by Django 5.0.2 on 2024-03-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quoteId', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('role', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('birthday', models.DateField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('startPrice', models.FloatField()),
                ('startAmount', models.FloatField()),
                ('progressDays', models.IntegerField()),
                ('progressAmount', models.IntegerField()),
                ('progressPrice', models.FloatField()),
                ('role', models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
    ]
